version: "2"
services:
  data:
    image: alpine
    command: echo Data Container
    user: 999:999

  dbstate:
    extends:
      file: docker-compose.yml
      service: data
    volumes:
      - /data/db
      
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes_from:
      - dbstate

  backend:
    image: svard/sl-dashboard:1.0.1
    ports:
      - "8087:8080"
    environment:
      HTTP_PORT: 8087

  frontend:
    image: svard/sl-dashboard:frontend-1.0.1
    ports:
      - "8088:80"